import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full m-0 p-0">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-300 antialiased flex flex-col w-full h-full m-0 p-0`}
      >
        <div className="bg-blue-500 text-white p-1 pl-4">
          <h1>PETs to Policy</h1>
        </div>
        <div className="h-full w-4/5 ml-auto mr-auto bg-white border-t-0 border-b-0 border-x-1 border-solid border-black p-2">
          {children}
        </div>
      </body>
    </html>
  );
}
